# Generated by Django 4.0.4 on 2022-04-28 08:53

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ToDoItem',
            fields=[
                ('status', models.BooleanField(auto_created=True)),
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('task', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('due_date', models.DateTimeField(default=datetime.datetime(2022, 5, 5, 8, 53, 45, 744058, tzinfo=utc))),
                ('created_date', models.DateTimeField(default=datetime.datetime(2022, 4, 28, 8, 53, 45, 745055, tzinfo=utc))),
                ('modification_date', models.DateTimeField(default=datetime.datetime(2022, 4, 28, 8, 53, 45, 745055, tzinfo=utc))),
                ('todo_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.todolist')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
    ]
