# Generated by Django 4.0.4 on 2022-04-28 08:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 28, 8, 54, 7, 318679, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 5, 8, 54, 7, 318679, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='modification_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 28, 8, 54, 7, 318679, tzinfo=utc)),
        ),
    ]
