# Generated by Django 4.0.4 on 2022-04-28 05:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_alter_todoitem_completion_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='completion_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 5, 5, 5, 21, 957135, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 28, 5, 5, 21, 957135, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 5, 5, 5, 21, 957135, tzinfo=utc)),
        ),
    ]
